### ISSUE TITLE
mise à jour déclaration en anglais

### ISSUE THREAD

**Issue by pya35** [Orange-OpenSource/La-Va11ydette#141]
- Modifier l'url du schéma pluriannuel par :` [the pluri-annual accessibility framework (PDF, 165Ko)](https://www.orange.com/sites/orangecom/files/2024-04/Digital_Accessibility_Multi-year_Plan_2024-2026_v1_1.pdf).
`

- Ajouter la mention (french) après le lien RGAA-WCAG : `<a href="https://a11y-guidelines.orange.com/fr/cadrage/correspondance-rgaa-wcag/">Here is the correspondence link between the RGAA and the WCAG (french)</a>`

- Traduire le défenseur des droits : `Write a message to the <a href="https://formulaire.defenseurdesdroits.fr/">Defender of Rights</a>  Or contact the <a href="https://www.defenseurdesdroits.fr/saisir/delegues">Defender of Rights delegate in your department</a>`

**Comment by MewenLeHo** [comment]
These issues were added to the new repository devoted to statement data files.
