### ISSUE TITLE
Revoir texte critère WCAG 1.4.10 AA (présence d'une barre de défilement horizontale ?)

### ISSUE THREAD

**Issue by MewenLeHo** [Orange-OpenSource/La-Va11ydette#150]
Le texte actuel : 

> À vérifier
> Vérifier qu'aucune barre de défilement n'apparait dans le sens horizontal.

devrait être modifié (par exemple) pour :

> À vérifier
> Vérifiez l'absence de barre de défilement horizontale sur la page. Si une barre de défilement horizontale est présente, assurez-vous qu'elle n'entrave pas la consultation du contenu.

**Comment by pya35** [comment]
proposition : " Vérifier que du contenu informatif ou des fonctionnalités ne sont ni tronqués nimasqués, et qui seraient visibles en faisant défiler la barre de défilement hozitontale"

**Comment by Aniort** [comment]
proposition : " Vérifier que du contenu informatif ou des fonctionnalités ne sont ni tronqués, ni masqués et utilisables sans utiliser la barre de défilement hozitontale"
