### ISSUE TITLE
Clés non renseignées dans la déclaration

### ISSUE THREAD

**Issue by pya35** [Orange-OpenSource/La-Va11ydette#152]
Quand on génère une déclaration FR ou EN, les noms de l'organisme et du projet ne sont pas renseignés

![image](https://github.com/user-attachments/assets/a1ef2c6a-1743-4a1b-b8e0-bfa51cafd8b7)

**Comment by MewenLeHo** [comment]
Ok je vois le problème.

Le bug vient de ma récente PR #137 où mon linter a remplacé les apostrophes typographiques par des apostrophes dactylographiques.

Par conséquent la génération de déclarations ne passait plus car [Nom de l’organisme concerné] est différent de [Nom de l'organisme concerné].

Je push un rollback de ces modifs non désirées dès maintenant.

**Comment by Aniort** [comment]
ok
