### ISSUE TITLE
Ajout d'un audit de conformité RAAM

### ISSUE THREAD

**Issue by RemiDormoy** [Orange-OpenSource/La-Va11ydette#165]
Bonjour, 

Serait il possible de rajouter une grille d'audit suivant les critères du RAAM qui va entrer en vigueur l'année prochaine ?

**Comment by pya35** [comment]
Bonjour @RemiDormoy , il n'est pas prévu à ce jour d'ajouter une grille RAAM. Nous essayons de maintenir et d'améliorer régulièrement nos propres grilles d'évaluation iOS et Android, qui s'appuient sur les WCAG 2.2. Si toutefois vous notez des manques ou des erreurs dans ces grilles, n'hésitez pas à nous faire un retour.
