### ISSUE TITLE
Zone d'import d'audit peu ergonomique

### ISSUE THREAD

**Issue by hannahiss** [Orange-OpenSource/La-Va11ydette#21]
La zone d'import d'un audit réalisé précédemment dans la va11ydette n'est pas très ergonomique :
![image](https://user-images.githubusercontent.com/16681352/152358704-6348f471-5cb1-4864-9cf6-6d860dfede93.png)

- on ne voit pas bien le bouton "Choisir un fichier" qui est à gauche, il n'a pas le look & feel d'un bouton (même si ça correspond au composant Boosted)
- "Sélectionner une fichier" fonctionne également comme le bouton "Choisir un fichier"
- Le bouton "Importer" à droite est confusant avec "Importer" au-dessus et avec "Choisir un fichier", il devrait être renommé "Charger le fichier" et éventuellement être désactivé tant qu'on n'a pas sélectionné un fichier ?

Peut-être utiliser plutôt le 4ème type de custom file input (https://boosted.orange.com/docs/5.1/forms/input-group/#custom-file-input) qui semble plus clair ? : 
![image](https://user-images.githubusercontent.com/16681352/152359549-8c0158a0-b75b-441a-8f9f-236fe59f5cd0.png)

Testé sur Chrome

**Comment by SimonF30** [comment]
hello @hannahiss , j'ai essayé d'améliorer l'ergonomie,

Je te met un petit screen,

Tu en penses quoi?

![image](https://user-images.githubusercontent.com/86358578/154438151-8200af86-71c0-4302-975d-e46ee4a2760b.png)

**Comment by hannahiss** [comment]
Concernant le wording, je mettrais 
"Choisir un fichier" et "Aucun fichier n'a été choisi" 
ou
"Sélectionner un fichier" et "Aucun fichier n'a été sélectionné" 
pour rester sur le même vocabulaire.
Ca me semble déjà mieux avec  "charger l'audit" en tout cas... :-)

**Comment by SimonF30** [comment]
Merged https://github.com/Orange-OpenSource/La-Va11ydette/pull/37
