### ISSUE TITLE
Modale d'ajout d'une page : valeur au lieu d'un placeholder

### ISSUE THREAD

**Issue by hannahiss** [Orange-OpenSource/La-Va11ydette#40]
Dans la modale d'ajout d'une page : 
![image](https://user-images.githubusercontent.com/16681352/164008720-a4281d22-a351-4f9b-9e26-ddc9501c93e2.png)
Le premier champ est pré-rempli avec "Nom de la page" au lieu d'un placeholder ou d'un libellé plus complet. C'est gênant quand on saisit pas mal de pages, car à chaque fois il faut vider le champ avant de saisir.

**Comment by SimonF30** [comment]
Le fait de pré-remplir avec "Nom de la Page" empêche de créer des pages sans nom,

Je préfere donc laisser le champ pré-rempli,

par contre, c'est vrai que l'expérience utilisateur n'est pas top.

Pour l'améliorer, je vais faire en sorte que le champ soit préselectionné comme ça on aura qu'à écrire le nouveau nom de page
