### ISSUE TITLE
Point de validation incomplet? : Rendre les intitulés des liens et des boutons accessibles / noms	

### ISSUE THREAD

**Issue by emilieviau** [Orange-OpenSource/La-Va11ydette#46]
Bonjour,

Concernant le critère  : "2.5.3 Label dans le nom A", vous avez le point de validation suivant : 
"Rendre les intitulés des liens et des boutons accessibles / noms". Dans les précisions sur la procédure de test, il est question de : "Localiser les liens, boutons et tout items de navigation" en lien avec la validation du critère.

Il serait bien d'introduire une mention explicite à l'effet que ce critère s'étend aussi aux champs de formulaires et à leurs étiquettes.  Si, par exemple, le nom accessible d'un champ de formulaire est redéfini et que celui-ci ne commence pas par les mêmes mots que l'étiquette visible, cela constituera un cas de non-conformité. Les utilisateurs de commandes vocales ne parviendront pas à sélectionner le champ sur la base de son étiquette visible.

**Comment by Aniort** [comment]
Merci de votre retour, 
on va rajouter la mention explicite lor&s d"e notre prochaine mise en prod #45 
bonne journée #
