### ISSUE TITLE
Amélioration "Appliquer automatiquement ce résultat aux nouvelles pages."

### ISSUE THREAD

**Issue by mathis94** [Orange-OpenSource/La-Va11ydette#55]
Il serait pratique d'avoir l'option "Appliquer automatiquement ce résultat aux nouvelles pages." valable sur toutes les pages.
Car par exemple si on audite la page d'accueil, puis une page contact et ensuite un formulaire de plusieurs pages, cette option disparait car accessible seulement pour la première page.

**Comment by mathis94** [comment]
> Merci pour votre retour, je vais essayer de voir comment l'améliorer

Merci !
de la part de Société générale

**Comment by SimonF30** [comment]
Mis à jours, la checkbox est maintenant disponible sur toutes les pages et permet de lier le test à la page suivante
