### ISSUE TITLE
Perte icone "Ce test est lié à la première page"

### ISSUE THREAD

**Issue by laurent-cintas** [Orange-OpenSource/La-Va11ydette#59]
Hello,

Lorsque la checkbox "Appliquer automatiquement ce résultat aux nouvelles pages." est cochée, une icône apparait à côte de l'état du critère (voir icon-link sur élément "Ce test est lié à la première page").

Hors cette icône a disparu (testé sur Chrome), pour afficher uniquement le fond jaune : 

![image](https://user-images.githubusercontent.com/44361341/179197648-37ed7b12-353c-4fcf-a641-0d8dc1d1ee22.png)

**Comment by SimonF30** [comment]
Yep, j'ai remarqué ça va être corriger avec cette PR #57

**Comment by laurent-cintas** [comment]
top !
